package com.practise.netty.test;

import java.util.concurrent.ExecutionException;

public class CompletableFutureTest {

    public static void main(String[] args) throws ExecutionException, InterruptedException {
//        CompletableFuture<String> future = CompletableFuture.supplyAsync(()->{
//            return "hello world";
//        });
//        System.out.println(future.get());  //阻塞的获取结果  ''helllo world"

        System.identityHashCode("");
    }
}
